name = "LFAToolkit"
uuid = "3f92b583-c0aa-4596-8bdf-f02f6c0a52df"
authors = ["Jed Brown <jed@jedbrown.org>", "Adeleke Bankoe <AdelekeBankole@colorado.edu>", "Jeremy L Thompson <thompson.jeremy.luke@gmail.com>"]
version = "0.6.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
FastGaussQuadrature = "0.4.9, 0.5"
Polynomials = "2.0.25"
julia = "1.3"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
